### ISSUE TITLE
impossible to use with sharedpreference

### ISSUE THREAD

**Issue by nitneuq33000** [boringdeveloper/FlutterSwitch#4]
hello, when I save bool statuts with sharedpreference and I load last value of statut I havn't change...

For exemple If my last statuts is true, and I load statut at the initStat I this print statuts : true but there is no switch of button...

**Comment by boringdeveloper** [comment]
Hi @nitneuq33000 , thank you for opening this issue. I have tagged a pull request for fix of this issue, Kindly check it out.

I made a demo using the changes in the package.
https://github.com/boringdeveloper/FlutterSwitchSharedPref

To try it out in your own project, depend on this version by putting these lines of code in your pubspec.yaml...

```yaml
flutter_switch:
    git:
      url: https://github.com/boringdeveloper/FlutterSwitch.git
      ref: 0.1.x
```
